version: "2"
services:
  percona:
    image: percona/percona-server:8.0
    container_name: perconaserver
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_DATABASE:
    ports: []
      # - "3306:3306"
    volumes:
      # create volumes for use
      - data:/var/lib/mysql
      # bind mount my local my.cnf
      # - $PWD/my.cnf:/etc/my.cnf
      - $PWD/my.cnf.d/mysqld-main.cnf:/etc/my.cnf.d/mysqld-main.cnf
    command:
      # Workaround for no my.cnf in image
      - '--user=mysql --disable-log-bin --default-authentication-plugin=mysql_native_password'
    restart: on-failure
volumes:
  data:
    driver: "local"
